### ISSUE TITLE
Enabling the Pull-Up Resistor on Bank Configuration Page Generates an Error

### ISSUE THREAD

**Issue by epbray1** [NIVeriStandAdd-Ons/SLSC-12201-DIO-Plugin-Custom-Device#1]
See the following [link ](https://forums.ni.com/t5/NI-VeriStand-Add-Ons-Discussions/SLSC-12201-DIO-Plugin-Custom-Device/td-p/3690527) for details.

**Comment by Alexbarp** [comment]
In version 1.0.3, I added the fix for this issue.
