### ISSUE TITLE
Builds are in the repo

### ISSUE THREAD

**Issue by tannerblair** [NIVeriStandAdd-Ons/SLSC-12201-DIO-Plugin-Custom-Device#4]

**Comment by jashnani** [comment]
I'm not migrating this issue to the [new location of this custom device](https://github.com/ni/niveristand-slsc-12201-custom-device) as it is not applicable.

**Comment by Alexbarp** [comment]
Closing this Issue because this has been migrated to the new custom device repository. For future development, use [niveristand-slsc-eds-custom-device](https://github.com/ni/niveristand-slsc-eds-custom-device)
